### ISSUE TITLE
Set up CI workflows

### ISSUE THREAD

**Issue by mwild1** [lunarmodules/lua-lace#2]
@alerque let me know if there are any prerequisites not yet met. I note that we don't have any luarocks packaging yet, but there is a luacheckrc.

**Update:** I've added a proposed rockspec at https://github.com/lunarmodules/lua-lace/tree/feature/add-rockspec so feel free to merge that branch if it looks good enough.

**Comment by alerque** [comment]
It looks like the [publish worked](https://luarocks.org/modules/lunarmodules/lua-lace). Ping me in an issue if anything needs fixing. To do tagged releases you'll want to create a `rockspecs` directory add appropriately named rockspecs to it, then tag the git commit (specifically the commit that adds them). You can see other modules in this repo that have followed that release pattern or I can help out with steps when the time comes to get the flow rigt.
